# Generated by Django 2.1.2 on 2019-01-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=12),
        ),
    ]
